version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elk/elasticsearch
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    environment:
      ES_JAVA_OPTS: "-Xmx2G -Xms2G -Duser.timezone=GMT-3"
      ELASTIC_PASSWORD: bhut@2020
    ports:
      - 9200:9200
    networks:
      - elk_stack
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: elk/kibana
    build:
      context: .
      dockerfile: docker/kibana/Dockerfile
    ports:
      - 5601:5601
    networks:
      - elk_stack
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: elk/logstash
    build:
      context: .
      dockerfile: docker/logstash/Dockerfile
    environment:
      LS_JAVA_OPTS: "-Xmx2G -Xms2G -Duser.timezone=GMT-3"
    ports:
      - 5000:5000
      - 9600:9600
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
    volumes:
      - ./app/database:/usr/share/logstash/logread

volumes:
  elasticsearch-data:

networks:
  elk_stack:
    driver: bridge